services:
  - type: web
    name: purplebot-official
    env: docker
    plan: free
    repo: https://github.com/SanneEmmanuel/PurpleBot-Official
    branch: main
    rootDir: .
    dockerfilePath: Dockerfile
